import React, { useEffect } from 'react';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import CodeEditor from '../BusinessComponents/Editor/CodeEditor';
import { useCookies } from 'react-cookie';

const RootPage: NextPage = () => {
  const [cookies, setCookie] = useCookies(['NEXT_COOKIE']);

  useEffect(() => {
    // const localeKey = 'NEXT_LOCALE';
    // setCookie(localeKey, 'en', { path: '/' });
  }, [setCookie]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Example 1</h1>
        <CodeEditor />
      </main>
    </div>
  );
};

export default RootPage;
