import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import ColorCard from '@/components/Cards/ColorCard';
import atlassian from '@/lib/theme/atlassian.json';

type PalletGroupsProps = {
  colors: string[];
};

const PalletGroups: React.FC<PalletGroupsProps> = ({ colors }) => {
  return (
    <div className="flex flex-row flex-wrap gap-4">
      {colors.map((color, index) => (
        <ColorCard name="primary" hex={color} key={index} />
      ))}
    </div>
  );
};

const spreadColors = (colors): string[] =>
  Object.entries(colors).map(entry => entry[1] as string);

const ColorsPage: NextPage = () => {
  const primaryPallets = [
    atlassian.primary,
    atlassian.primaryDark,
    atlassian.white
  ];
  const secondaryPallets = [
    '#FF5630',
    '#FFAB00',
    '#36B37E',
    '#00B8D9',
    '#6554C0'
  ];
  const darkNeutralsPallets = spreadColors(atlassian.darkNeutral);
  const midNeutralsPallets = spreadColors(atlassian.neutral);
  const lightNeutralsPallets = spreadColors(atlassian.lightNeutral);
  const redPallets = spreadColors(atlassian.red);
  const yellowPallets = spreadColors(atlassian.yellow);
  const greenPallets = spreadColors(atlassian.green);
  const bluePallets = spreadColors(atlassian.blue);
  const tealPallets = spreadColors(atlassian.teal);
  const purplePallets = spreadColors(atlassian.purple);

  return (
    <div>
      <Head>
        <title>Color Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-lightneutral-200 p-16 dark:bg-darkneutral-500">
          <h1 className="mb-3 text-5xl">Color</h1>
          <p>A brand distinguisher</p>
        </div>
        <section>
          <div className="py-2">
            <h1 className="pb-2 text-2xl">Primary palette</h1>
            <PalletGroups colors={primaryPallets} />
          </div>
          <div className="py-2">
            <h1 className="pb-2 text-2xl">Secondary palette</h1>
            <PalletGroups colors={secondaryPallets} />
          </div>
          <div className="py-2">
            <h1 className="py-2 pb-2 text-2xl">Extended palette</h1>
            <div className="pb-2">
              <h1 className="pb-2 text-xl">Dark neutrals</h1>
              <PalletGroups colors={darkNeutralsPallets} />
            </div>
            <div className="pb-2">
              <h1 className="pb-2 text-xl">Mid neutrals</h1>
              <PalletGroups colors={midNeutralsPallets} />
            </div>
            <div className="pb-2">
              <h1 className="pb-2 text-xl">Dark neutrals</h1>
              <PalletGroups colors={lightNeutralsPallets} />
            </div>
          </div>
          <div className="py-2">
            <h1 className="pb-2 text-2xl">Red palette</h1>
            <PalletGroups colors={redPallets} />
          </div>
          <div className="py-2">
            <h1 className="pb-2 text-2xl">Yellow palette</h1>
            <PalletGroups colors={yellowPallets} />
          </div>
          <div className="py-2">
            <h1 className="pb-2 text-2xl">Green palette</h1>
            <PalletGroups colors={greenPallets} />
          </div>
          <div className="py-2">
            <h1 className="pb-2 text-2xl">Blue palette</h1>
            <PalletGroups colors={bluePallets} />
          </div>
          <div className="py-2">
            <h1 className="pb-2 text-2xl">Teal palette</h1>
            <PalletGroups colors={tealPallets} />
          </div>
          <div className="py-2">
            <h1 className="pb-2 text-2xl">Purple palette</h1>
            <PalletGroups colors={purplePallets} />
          </div>
        </section>
        <section>
          <h1 className="pb-2 text-2xl">Semantic color</h1>
        </section>
      </main>
    </div>
  );
};

export default ColorsPage;
