import React, { useEffect } from 'react';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import { useCookies } from 'react-cookie';
import Button, { ButtonGroup } from '@/components/Button';

const RootPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <nav className="h-20 bg-neutral-400">Nav Bar</nav>
        <section>
          <div>
            <h1>Committed to improving the lives of patients worldwide</h1>
            <p>
              An awesome and powerful tool for your business, increase business
              revenue wiht enterpricse grade components built to acquire and
              engage customers
            </p>
            <ButtonGroup>
              <Button appearance="primary">Live Preview</Button>
              <Button appearance="subtle-link">Buy The Damn Thing</Button>
            </ButtonGroup>
          </div>
        </section>
      </main>
    </div>
  );
};

export default RootPage;
