import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import CodeEditor from '../BusinessComponents/Editor/CodeEditor';

const RootPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Example 1</h1>
        <CodeEditor />
      </main>
    </div>
  );
};

export default RootPage;
