import React, { useEffect } from 'react';
import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import { useCookies } from 'react-cookie';

const RootPage: NextPage = () => {
  const [cookies, setCookie] = useCookies(['NEXT_COOKIE']);

  useEffect(() => {
    // setCookie('NEXT_LOCALE', 'en', { path: '/' });
  }, [setCookie]);

  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button
          type="button"
          className="to-pink-500px-4 from-indigo-500 rounded-lg bg-gradient-to-r via-purple-500 py-2 "
        >
          Hover me
        </button>
      </main>
    </div>
  );
};

export default RootPage;
